FROM python:3.12-slim

WORKDIR /app

# Install only what is necessary for Postgres & Math
RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Force a long timeout and use the smaller CPU-only torch index
RUN pip install --default-timeout=1000 --no-cache-dir \
    -r requirements.txt \
    --extra-index-url https://download.pytorch.org/whl/cpu

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]